### ISSUE TITLE
TypeError: torch._VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing'

### ISSUE THREAD

**Issue by YiiiiZhang** [duongtruongbinh/YOLOv8-Object-Detection#1]
![image](https://github.com/duongtruongbinh/YOLOv8-Object-Detection/assets/80152980/79aa3c62-58da-4a4d-89be-76f3e2f77391)
![image](https://github.com/duongtruongbinh/YOLOv8-Object-Detection/assets/80152980/943acf8e-0377-4ee1-94bf-5f0c901ce95f)

**Comment by duongtruongbinh** [comment]
@JOKER-3-z I have never encountered this error before. I asked ChatGPT about it, and GPT responded that the error message TypeError: torch._VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing' occurs when the 'indexing' keyword argument is provided multiple times to the torch.meshgrid() function. To fix this issue, ensure that the 'indexing' argument is given only once in the function call."

**Comment by YiiiiZhang** [comment]
Thanks bro , i will search this problem
